// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhdonjDLA0YUL-Hx8kUh45ASJzlHwGK8',
    appId: '1:907615055976:web:5c59c5b168bfc9950fcbdd',
    messagingSenderId: '907615055976',
    projectId: 'productform-1da60',
    authDomain: 'productform-1da60.firebaseapp.com',
    storageBucket: 'productform-1da60.appspot.com',
    measurementId: 'G-6D316SD0T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5OFPJjy7l5TckECidXJMzSTfcWTiAA-0',
    appId: '1:907615055976:android:9ddec9068457f26f0fcbdd',
    messagingSenderId: '907615055976',
    projectId: 'productform-1da60',
    storageBucket: 'productform-1da60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8SKyBpX0iWUI8GANQuyuMaSLgONW4JBQ',
    appId: '1:907615055976:ios:c064584c7e923b800fcbdd',
    messagingSenderId: '907615055976',
    projectId: 'productform-1da60',
    storageBucket: 'productform-1da60.appspot.com',
    iosBundleId: 'com.example.productform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8SKyBpX0iWUI8GANQuyuMaSLgONW4JBQ',
    appId: '1:907615055976:ios:c064584c7e923b800fcbdd',
    messagingSenderId: '907615055976',
    projectId: 'productform-1da60',
    storageBucket: 'productform-1da60.appspot.com',
    iosBundleId: 'com.example.productform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwhdonjDLA0YUL-Hx8kUh45ASJzlHwGK8',
    appId: '1:907615055976:web:e754ea2bc1728d610fcbdd',
    messagingSenderId: '907615055976',
    projectId: 'productform-1da60',
    authDomain: 'productform-1da60.firebaseapp.com',
    storageBucket: 'productform-1da60.appspot.com',
    measurementId: 'G-277LBCFC1Z',
  );
}
